import Link from "next/link";
import { LuArrowLeft } from "react-icons/lu";

const LAST_UPDATED = "June 7, 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-base font-black uppercase tracking-[0.18em] text-primary/80">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-foreground/65">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="relative flex-1 overflow-hidden bg-background px-6 py-12">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_center,rgba(11,175,231,0.06),transparent_40%)]" />

      <div className="relative mx-auto max-w-2xl animate-fade-in">
        <Link
          href="/register"
          className="mb-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-foreground/40 transition-colors hover:text-primary"
        >
          <LuArrowLeft className="h-3.5 w-3.5" />
          Back
        </Link>

        <div className="glass rounded-xl border border-white/[0.08] px-7 py-8 shadow-[0_8px_40px_rgba(0,0,0,0.4)]">
          {/* Header */}
          <div className="mb-8 border-b border-white/[0.07] pb-6">
            <h1 className="text-3xl font-black uppercase tracking-tight text-foreground">
              Terms &amp; Privacy Policy
            </h1>
            <p className="mt-2 text-xs text-foreground/35 tracking-widest uppercase">
              FishTyping · Last updated {LAST_UPDATED}
            </p>
          </div>

          <div className="space-y-8">
            {/* ── Terms of Service ── */}
            <div className="space-y-6">
              <h2 className="text-xs font-black uppercase tracking-[0.3em] text-foreground/25">
                Terms of Service
              </h2>

              <Section title="1. Acceptance">
                <p>
                  By creating an account or using FishTyping you agree to these terms. If you do not
                  agree, do not use the service.
                </p>
              </Section>

              <Section title="2. Eligibility">
                <p>
                  You must be at least 13 years old to create an account. By registering you confirm
                  that you meet this requirement.
                </p>
              </Section>

              <Section title="3. Accounts">
                <p>You are responsible for keeping your credentials secure. One account per person.</p>
                <p>
                  We reserve the right to suspend or remove accounts that violate these terms, abuse
                  the platform, or engage in disruptive behaviour.
                </p>
              </Section>

              <Section title="4. Fair Play">
                <p>
                  Automated tools, bots, scripts, or any other means of artificially inflating typing
                  scores are strictly prohibited. Leaderboard rankings must reflect genuine typing
                  performance.
                </p>
              </Section>

              <Section title="5. Content">
                <p>
                  Typing passages are generated by AI (Google Gemini) or added manually by admins.
                  We make no guarantees about the accuracy or completeness of passage content.
                </p>
              </Section>

              <Section title="6. Availability">
                <p>
                  FishTyping is provided <strong className="text-foreground/80">as-is</strong> with no
                  uptime guarantee. We may modify, suspend, or discontinue the service at any time
                  without prior notice.
                </p>
              </Section>

              <Section title="7. Limitation of Liability">
                <p>
                  FishTyping is not liable for any direct, indirect, or consequential damages arising
                  from your use of the service.
                </p>
              </Section>
            </div>

            <div className="h-px bg-white/[0.06]" />

            {/* ── Privacy Policy ── */}
            <div className="space-y-6">
              <h2 className="text-xs font-black uppercase tracking-[0.3em] text-foreground/25">
                Privacy Policy
              </h2>

              <Section title="1. What We Collect">
                <p>When you create an account we collect:</p>
                <ul className="ml-4 list-disc space-y-1 marker:text-primary/40">
                  <li>Email address</li>
                  <li>Display name and avatar</li>
                  <li>Typing results — WPM, accuracy, duration, difficulty level</li>
                  <li>Preferred language setting</li>
                </ul>
                <p className="mt-2">
                  If you sign in with Google or GitHub, we receive only the profile data those
                  providers share (name, email, avatar).
                </p>
              </Section>

              <Section title="2. How We Use It">
                <p>Your data is used solely to:</p>
                <ul className="ml-4 list-disc space-y-1 marker:text-primary/40">
                  <li>Authenticate you and maintain your session</li>
                  <li>Display your personal typing statistics and history</li>
                  <li>Power the global leaderboard (Expert difficulty only)</li>
                  <li>Personalise passage delivery based on your settings</li>
                </ul>
              </Section>

              <Section title="3. Third-Party Services">
                <p>FishTyping uses the following third-party services:</p>
                <ul className="ml-4 list-disc space-y-1 marker:text-primary/40">
                  <li>
                    <strong className="text-foreground/80">Firebase Authentication</strong> — handles
                    sign-in and session management
                  </li>
                  <li>
                    <strong className="text-foreground/80">Supabase</strong> — stores user profiles,
                    passages, and typing history
                  </li>
                  <li>
                    <strong className="text-foreground/80">Google Gemini AI</strong> — generates
                    typing passages; no personal data is included in prompts
                  </li>
                </ul>
                <p className="mt-2">Each provider has its own privacy policy that governs their handling of data.</p>
              </Section>

              <Section title="4. Data Sharing">
                <p>
                  We do not sell, rent, or share your personal data with third parties for marketing
                  purposes. Leaderboard entries (display name and score) are visible to all users.
                </p>
              </Section>

              <Section title="5. Data Retention">
                <p>
                  Your account data is retained for as long as your account exists. You may request
                  deletion by contacting us at the email below.
                </p>
              </Section>

              <Section title="6. Security">
                <p>
                  We use industry-standard practices to protect your data. However, no system is
                  completely secure and we cannot guarantee absolute security.
                </p>
              </Section>

              <Section title="7. Contact">
                <p>
                  Questions about these terms or your data? Reach us at{" "}
                  <a
                    href="mailto:touxhk@gmail.com"
                    className="font-bold text-primary hover:text-primary/80 transition-colors"
                  >
                    touxhk@gmail.com
                  </a>
                  .
                </p>
              </Section>
            </div>
          </div>

          {/* Footer note */}
          <div className="mt-10 border-t border-white/[0.07] pt-6 text-center">
            <p className="text-xs text-foreground/30">
              By creating an account you agree to these terms.
            </p>
            <Link
              href="/register"
              className="mt-3 inline-flex items-center gap-1.5 text-xs font-bold text-primary/70 transition-colors hover:text-primary"
            >
              <LuArrowLeft className="h-3 w-3" />
              Back to Register
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
