-- SQL Script to Insert Passages into Database
-- Run this in your Supabase SQL Editor
-- This creates passages for all difficulty levels (beginner, advanced, expert)

-- ============================================
-- BEGINNER PASSAGES (15-30 words)
-- ============================================

INSERT INTO passages (content, language, difficulty, length, status, generated_by, word_count)
VALUES
-- English Beginner
('The cat sat on the mat. It was warm and sunny. Birds sang in the trees nearby.', 'english', 'beginner', 'medium', 'ready', 'manual', 18),
('I like to read books every day. They are fun and interesting. Reading helps me learn new things.', 'english', 'beginner', 'medium', 'ready', 'manual', 21),
('The dog runs fast in the park. It plays with children. Everyone laughs and has fun together.', 'english', 'beginner', 'medium', 'ready', 'manual', 20),
('We go to school to learn. Teachers help us understand math and science. Education is very important.', 'english', 'beginner', 'medium', 'ready', 'manual', 19),
('The sun is bright today. It gives us light and warmth. Plants need sunshine to grow tall.', 'english', 'beginner', 'medium', 'ready', 'manual', 20),
('My friend likes to play games. We have fun after school. Playing together makes us happy.', 'english', 'beginner', 'medium', 'ready', 'manual', 18),
('The ocean is very big and blue. Fish swim in the water. Waves crash on the sandy beach.', 'english', 'beginner', 'medium', 'ready', 'manual', 20),
('I eat healthy food every day. Fruits and vegetables are good for me. Drinking water keeps me strong.', 'english', 'beginner', 'medium', 'ready', 'manual', 20),
('Birds fly high in the sky. They build nests in tall trees. Baby birds learn to fly from their parents.', 'english', 'beginner', 'medium', 'ready', 'manual', 21),
('The moon shines at night. Stars twinkle in the dark sky. The night is peaceful and quiet.', 'english', 'beginner', 'medium', 'ready', 'manual', 19),

-- Lao Beginner
('ແມວນັ່ງຢູ່ເທິງເສື່ອ. ມັນອົບອຸ່ນແລະມີແສງແດດ. ນົກຮ້ອງຢູ່ໃນຕົ້ນໄມ້ໃກ້ໆ.', 'lao', 'beginner', 'medium', 'ready', 'manual', 15),
('ຂ້ອຍມັກອ່ານຫນັງສືທຸກມື້. ມັນສະໜຸກແລະໜ້າສົນໃຈ. ການອ່ານຊ່ວຍໃຫ້ຂ້ອຍຮຽນຮູ້ສິ່ງໃໝ່.', 'lao', 'beginner', 'medium', 'ready', 'manual', 16),
('ໝາແລ່ນໄວໃນສວນສາທາລະນະ. ມັນຫຼິ້ນກັບເດັກນ້ອຍ. ທຸກຄົນຫົວແລະມີຄວາມສຸກຮ່ວມກັນ.', 'lao', 'beginner', 'medium', 'ready', 'manual', 15),
('ພວກເຮົາໄປໂຮງຮຽນເພື່ອຮຽນ. ຄູສອນຊ່ວຍພວກເຮົາເຂົ້າໃຈຄະນິດສາດແລະວິທະຍາສາດ. ການສຶກສາສຳຄັນຫຼາຍ.', 'lao', 'beginner', 'medium', 'ready', 'manual', 16),
('ແສງແດດສ່ອງແຈ້ງໃນມື້ນີ້. ມັນໃຫ້ແສງສະຫວ່າງແລະຄວາມອົບອຸ່ນ. ພືດຕ້ອງການແສງແດດເພື່ອເຕີບໃຫຍ່.', 'lao', 'beginner', 'medium', 'ready', 'manual', 15);

-- ============================================
-- ADVANCED PASSAGES (100-150 words)
-- ============================================

INSERT INTO passages (content, language, difficulty, length, status, generated_by, word_count)
VALUES
-- English Advanced
('Technology has revolutionized the way we communicate and interact with each other in modern society. From smartphones to social media platforms, digital innovation continues to shape our daily lives in unprecedented ways. The internet connects billions of people across the globe, enabling instant communication and information sharing. Cloud computing allows us to access our data from anywhere, while artificial intelligence assists us in making better decisions. However, these advancements also bring challenges such as privacy concerns, digital addiction, and the spread of misinformation. As we embrace new technologies, it is crucial to maintain a balance between innovation and responsibility. Education systems must adapt to prepare students for a digital future, teaching not only technical skills but also critical thinking and digital literacy.', 'english', 'advanced', 'medium', 'ready', 'manual', 125),

('Climate change represents one of the most pressing challenges facing humanity today. Rising global temperatures are causing ice caps to melt, sea levels to rise, and weather patterns to become increasingly unpredictable. Scientists warn that without immediate action to reduce greenhouse gas emissions, the consequences could be catastrophic. Renewable energy sources such as solar, wind, and hydroelectric power offer promising alternatives to fossil fuels. Governments worldwide are implementing policies to encourage sustainable practices and reduce carbon footprints. Individuals can also make a difference by adopting eco-friendly habits like recycling, using public transportation, and reducing energy consumption. The transition to a sustainable future requires collective effort from governments, businesses, and citizens. By working together and making conscious choices, we can protect our planet for future generations.', 'english', 'advanced', 'medium', 'ready', 'manual', 130),

('The human brain is one of the most complex and fascinating organs in the body. It contains approximately eighty-six billion neurons that communicate through electrical and chemical signals. These neurons form intricate networks that enable us to think, feel, remember, and make decisions. Neuroscience research has revealed that the brain is remarkably plastic, meaning it can reorganize itself by forming new neural connections throughout life. This neuroplasticity allows us to learn new skills, adapt to changing environments, and recover from injuries. Memory formation involves multiple brain regions working together to encode, store, and retrieve information. Understanding how the brain works has important implications for treating neurological disorders, improving education, and enhancing cognitive performance. As technology advances, brain imaging techniques provide deeper insights into the mysteries of human consciousness and cognition.', 'english', 'advanced', 'medium', 'ready', 'manual', 140),

('Space exploration has captured human imagination for centuries, driving scientific discovery and technological innovation. The launch of Sputnik in nineteen fifty-seven marked the beginning of the space age, followed by the historic moon landing in nineteen sixty-nine. Today, space agencies and private companies are working together to push the boundaries of what is possible. Mars missions aim to search for signs of past or present life on the red planet. The International Space Station serves as a laboratory for conducting experiments in microgravity. Satellite technology has transformed communication, navigation, and weather forecasting on Earth. Looking ahead, ambitious projects include establishing permanent lunar bases and sending humans to Mars. These endeavors not only expand our knowledge of the universe but also inspire future generations to pursue careers in science and engineering.', 'english', 'advanced', 'medium', 'ready', 'manual', 145),

('Artificial intelligence is transforming industries and reshaping the future of work. Machine learning algorithms can analyze vast amounts of data to identify patterns and make predictions with remarkable accuracy. AI applications range from virtual assistants and recommendation systems to autonomous vehicles and medical diagnosis. In healthcare, AI helps doctors detect diseases earlier and develop personalized treatment plans. In finance, algorithms detect fraudulent transactions and optimize investment strategies. Manufacturing benefits from AI-powered robots that increase efficiency and precision. However, the rise of AI also raises important questions about job displacement, algorithmic bias, and ethical considerations. As AI systems become more sophisticated, society must ensure they are developed and deployed responsibly. Education and training programs need to prepare workers for an AI-driven economy while addressing concerns about privacy and security.', 'english', 'advanced', 'medium', 'ready', 'manual', 142),

-- Lao Advanced
('ເຕັກໂນໂລຊີໄດ້ປ່ຽນແປງວິທີທີ່ພວກເຮົາສື່ສານແລະພົວພັນກັນໃນສັງຄົມທີ່ທັນສະໄໝ. ຈາກໂທລະສັບສະຫຼາດໄປຫາເວທີສື່ສັງຄົມອອນໄລນ໌, ນະວັດຕະກຳດິຈິຕອນຍັງສືບຕໍ່ສ້າງຮູບແບບຊີວິດປະຈຳວັນຂອງພວກເຮົາໃນທາງທີ່ບໍ່ເຄີຍມີມາກ່ອນ. ອິນເຕີເນັດເຊື່ອມຕໍ່ຜູ້ຄົນຫຼາຍພັນລ້ານຄົນທົ່ວໂລກ, ເຮັດໃຫ້ການສື່ສານແລະການແບ່ງປັນຂໍ້ມູນເປັນໄປໄດ້ທັນທີ. ການຄຳນວນແບບຄລາວອະນຸຍາດໃຫ້ພວກເຮົາເຂົ້າເຖິງຂໍ້ມູນຂອງພວກເຮົາຈາກທຸກບ່ອນ, ໃນຂະນະທີ່ປັນຍາປະດິດຊ່ວຍພວກເຮົາໃນການຕັດສິນໃຈທີ່ດີກວ່າ. ຢ່າງໃດກໍຕາມ, ຄວາມກ້າວໜ້າເຫຼົ່ານີ້ຍັງນຳມາເຊິ່ງສິ່ງທ້າທາຍເຊັ່ນ: ຄວາມກັງວົນກ່ຽວກັບຄວາມເປັນສ່ວນຕົວ, ການຕິດດິຈິຕອນ, ແລະການແຜ່ກະຈາຍຂໍ້ມູນທີ່ບໍ່ຖືກຕ້ອງ.', 'lao', 'advanced', 'medium', 'ready', 'manual', 110);

-- ============================================
-- EXPERT PASSAGES (200-300 words)
-- ============================================

INSERT INTO passages (content, language, difficulty, length, status, generated_by, word_count)
VALUES
-- English Expert
('The intersection of quantum mechanics and computer science has given rise to quantum computing, a revolutionary paradigm that promises to solve problems currently intractable for classical computers. Unlike traditional bits that exist in states of zero or one, quantum bits or qubits can exist in superposition, simultaneously representing multiple states. This fundamental property, combined with quantum entanglement, enables quantum computers to perform certain calculations exponentially faster than their classical counterparts. Researchers are exploring applications in cryptography, drug discovery, financial modeling, and optimization problems. However, significant technical challenges remain before quantum computers can achieve practical utility at scale. Maintaining quantum coherence requires extremely low temperatures and isolation from environmental interference. Error correction in quantum systems is fundamentally different from classical computing and requires sophisticated protocols. Despite these obstacles, major technology companies and research institutions are investing heavily in quantum computing development. The race to achieve quantum supremacy has intensified, with various organizations claiming milestones in demonstrating quantum advantage for specific tasks. As the field matures, quantum computing may fundamentally transform industries and scientific research, opening new frontiers in our understanding of computation and information processing. The implications extend beyond mere computational speed, potentially revolutionizing fields such as materials science, artificial intelligence, and our understanding of the universe itself.', 'english', 'expert', 'medium', 'ready', 'manual', 215),

('Neuroscience has made remarkable strides in understanding the intricate workings of the human brain, yet many mysteries remain unsolved. The brain contains approximately eighty-six billion neurons, each forming thousands of connections with other neurons, creating a network of staggering complexity. Recent advances in neuroimaging techniques such as functional magnetic resonance imaging and positron emission tomography have allowed researchers to observe brain activity in real time, revealing how different regions coordinate to produce thoughts, emotions, and behaviors. Studies of neuroplasticity demonstrate that the brain retains remarkable capacity for adaptation and reorganization throughout life, challenging earlier assumptions about fixed neural architecture. Understanding consciousness remains one of the greatest challenges in neuroscience, with competing theories attempting to explain how subjective experience emerges from physical processes. Research into neurodegenerative diseases like Alzheimers and Parkinsons seeks to identify mechanisms of neuronal death and develop therapeutic interventions. The emerging field of computational neuroscience uses mathematical models and computer simulations to understand neural systems at multiple scales, from individual neurons to large-scale brain networks. As technology advances and interdisciplinary collaboration increases, neuroscience continues to illuminate the biological basis of human cognition and behavior, offering hope for treating mental illness and enhancing human potential.', 'english', 'expert', 'medium', 'ready', 'manual', 220),

('The global economy has undergone profound transformations in recent decades, driven by technological innovation, globalization, and shifting geopolitical dynamics. International trade has expanded dramatically, connecting markets across continents and creating complex supply chains that span the globe. Financial markets have become increasingly interconnected, with capital flowing freely across borders in search of investment opportunities. The rise of emerging economies, particularly in Asia, has shifted the balance of economic power and created new centers of innovation and growth. Digital currencies and blockchain technology are challenging traditional financial systems and raising questions about the future of money. Income inequality has widened in many countries, sparking debates about economic policy and social justice. Climate change poses significant risks to economic stability, requiring massive investments in sustainable infrastructure and clean energy. The COVID-nineteen pandemic exposed vulnerabilities in global supply chains and accelerated trends toward remote work and digital transformation. Central banks face the challenge of managing inflation while supporting economic recovery. Trade tensions between major powers threaten to fragment the global economy into competing blocs. As we navigate these challenges, policymakers must balance economic growth with environmental sustainability and social equity, ensuring that prosperity is shared broadly and future generations inherit a stable and thriving world economy.', 'english', 'expert', 'medium', 'ready', 'manual', 235);

-- Verify the inserts
SELECT difficulty, language, COUNT(*) as count, AVG(word_count) as avg_words
FROM passages
GROUP BY difficulty, language
ORDER BY difficulty, language;