-- SQL Script to Insert Initial Passages
-- Run this in your Supabase SQL Editor to populate the database with initial passages

-- Beginner passages (15-30 words)
INSERT INTO passages (content, language, difficulty, length, theme, challenge_type, status, generated_by, word_count)
VALUES
('The cat sat on the mat. It was warm and sunny. Birds sang in the trees nearby.', 'english', 'beginner', 'short', 'general', 'standard', 'ready', 'manual', 18),
('I like to read books. They are fun and interesting. Reading helps me learn new things every day.', 'english', 'beginner', 'short', 'general', 'standard', 'ready', 'manual', 20),
('The dog runs fast. It plays in the park. Children laugh and have fun with their pets.', 'english', 'beginner', 'short', 'general', 'standard', 'ready', 'manual', 19),
('We go to school. We learn math and science. Teachers help us understand new concepts and ideas.', 'english', 'beginner', 'short', 'general', 'standard', 'ready', 'manual', 20),
('The sun is bright. It gives us light and warmth. Plants need sunshine to grow tall and strong.', 'english', 'beginner', 'short', 'nature', 'standard', 'ready', 'manual', 21);

-- Intermediate passages (40-80 words)
INSERT INTO passages (content, language, difficulty, length, theme, challenge_type, status, generated_by, word_count)
VALUES
('The quick brown fox jumps over the lazy dog and then runs away into the deep blue ocean to find some fish to eat. The water is cold but the fox is brave and determined to catch its dinner before sunset arrives.', 'english', 'intermediate', 'medium', 'general', 'standard', 'ready', 'manual', 50),
('Technology has changed our lives in many ways. We use computers and smartphones every day to communicate with friends and family. The internet connects people from all around the world, making it easier to share ideas and information instantly.', 'english', 'intermediate', 'medium', 'technology', 'standard', 'ready', 'manual', 45),
('Nature is full of beautiful sights and sounds. Birds sing in the morning while flowers bloom in colorful gardens. Trees provide shade and fresh air for everyone to enjoy. Taking time to appreciate nature helps us feel peaceful and relaxed.', 'english', 'intermediate', 'medium', 'nature', 'standard', 'ready', 'manual', 48),
('Learning new skills takes practice and patience. Whether you are studying a language or playing an instrument, consistent effort leads to improvement. Setting small goals and celebrating progress along the way keeps you motivated to continue learning.', 'english', 'intermediate', 'medium', 'general', 'standard', 'ready', 'manual', 45),
('Exercise is important for staying healthy and strong. Regular physical activity improves your mood and energy levels. You can walk, run, swim, or play sports to keep your body active. Even small amounts of movement each day make a big difference.', 'english', 'intermediate', 'medium', 'general', 'standard', 'ready', 'manual', 48);

-- Advanced passages (100-150 words)
INSERT INTO passages (content, language, difficulty, length, theme, challenge_type, status, generated_by, word_count)
VALUES
('Artificial intelligence has become an integral part of modern society, transforming industries and reshaping how we interact with technology. Machine learning algorithms analyze vast amounts of data to identify patterns and make predictions with remarkable accuracy. From virtual assistants to autonomous vehicles, AI applications continue to expand into new domains. However, these advancements also raise important ethical questions about privacy, bias, and the future of employment. As AI systems become more sophisticated, society must carefully consider how to harness their potential while mitigating potential risks. Developing responsible AI requires collaboration between technologists, policymakers, and ethicists to ensure these powerful tools benefit humanity as a whole.', 'english', 'advanced', 'long', 'technology', 'standard', 'ready', 'manual', 115),
('Climate change represents one of the most pressing challenges facing our planet today. Rising global temperatures are causing ice caps to melt, sea levels to rise, and weather patterns to become increasingly unpredictable. Scientists warn that without significant action to reduce greenhouse gas emissions, the consequences could be catastrophic for future generations. Renewable energy sources such as solar and wind power offer promising alternatives to fossil fuels. Governments, businesses, and individuals all have important roles to play in addressing this crisis. By making sustainable choices and supporting environmental policies, we can work together to protect our planet and ensure a livable world for those who come after us.', 'english', 'advanced', 'long', 'science', 'standard', 'ready', 'manual', 120),
('The history of human civilization is marked by remarkable achievements and profound challenges. Ancient societies developed complex systems of writing, mathematics, and governance that laid the foundation for modern culture. The Renaissance sparked an explosion of artistic and scientific innovation that transformed European society. The Industrial Revolution brought unprecedented technological progress but also created new social problems. Throughout history, people have struggled with questions of justice, equality, and human rights. Understanding our past helps us navigate present challenges and build a better future. By studying history, we gain perspective on the forces that shape our world and the choices that define our collective destiny.', 'english', 'advanced', 'long', 'history', 'standard', 'ready', 'manual', 125);

-- Expert passages (200-300 words)
INSERT INTO passages (content, language, difficulty, length, theme, challenge_type, status, generated_by, word_count)
VALUES
('The intersection of quantum mechanics and computer science has given rise to quantum computing, a revolutionary paradigm that promises to solve problems currently intractable for classical computers. Unlike traditional bits that exist in states of zero or one, quantum bits or qubits can exist in superposition, simultaneously representing multiple states. This fundamental property, combined with quantum entanglement, enables quantum computers to perform certain calculations exponentially faster than their classical counterparts. Researchers are exploring applications in cryptography, drug discovery, financial modeling, and optimization problems. However, significant technical challenges remain before quantum computers can achieve practical utility at scale. Maintaining quantum coherence requires extremely low temperatures and isolation from environmental interference. Error correction in quantum systems is fundamentally different from classical computing and requires sophisticated protocols. Despite these obstacles, major technology companies and research institutions are investing heavily in quantum computing development. The race to achieve quantum supremacy has intensified, with various organizations claiming milestones in demonstrating quantum advantage for specific tasks. As the field matures, quantum computing may fundamentally transform industries and scientific research, opening new frontiers in our understanding of computation and information processing.', 'english', 'expert', 'long', 'technology', 'standard', 'ready', 'manual', 210),
('Neuroscience has made remarkable strides in understanding the intricate workings of the human brain, yet many mysteries remain unsolved. The brain contains approximately eighty-six billion neurons, each forming thousands of connections with other neurons, creating a network of staggering complexity. Recent advances in neuroimaging techniques such as functional magnetic resonance imaging and positron emission tomography have allowed researchers to observe brain activity in real time, revealing how different regions coordinate to produce thoughts, emotions, and behaviors. Studies of neuroplasticity demonstrate that the brain retains remarkable capacity for adaptation and reorganization throughout life, challenging earlier assumptions about fixed neural architecture. Understanding consciousness remains one of the greatest challenges in neuroscience, with competing theories attempting to explain how subjective experience emerges from physical processes. Research into neurodegenerative diseases like Alzheimers and Parkinsons seeks to identify mechanisms of neuronal death and develop therapeutic interventions. The emerging field of computational neuroscience uses mathematical models and computer simulations to understand neural systems at multiple scales, from individual neurons to large-scale brain networks. As technology advances and interdisciplinary collaboration increases, neuroscience continues to illuminate the biological basis of human cognition and behavior.', 'english', 'expert', 'long', 'science', 'standard', 'ready', 'manual', 220);

-- Add some passages with punctuation challenge
INSERT INTO passages (content, language, difficulty, length, theme, challenge_type, status, generated_by, word_count)
VALUES
('The cat—fluffy, orange, and utterly fearless—stared at the dog; the dog, surprised, backed away slowly. "What courage!" thought the owner, watching from the window.', 'english', 'intermediate', 'medium', 'general', 'punctuation', 'ready', 'manual', 28),
('Technology evolves rapidly: smartphones, tablets, laptops—all connected seamlessly. Users (young and old) adapt quickly; however, privacy concerns remain significant. "Is convenience worth the cost?" many ask.', 'english', 'intermediate', 'medium', 'technology', 'punctuation', 'ready', 'manual', 30);

-- Add some passages with numbers
INSERT INTO passages (content, language, difficulty, length, theme, challenge_type, status, generated_by, word_count)
VALUES
('The project cost $150,000 and affected 8 million people across 50 different countries. Test scores increased by 25% in just 3 months, showing significant improvement in student performance.', 'english', 'intermediate', 'medium', 'general', 'numbers', 'ready', 'manual', 32),
('In 2024, the company reported revenue of $2.5 billion, a 15% increase from the previous year. The stock price rose from $45 to $67, representing a 48.9% gain for investors.', 'english', 'intermediate', 'medium', 'general', 'numbers', 'ready', 'manual', 35);

-- Add some speed passages
INSERT INTO passages (content, language, difficulty, length, theme, challenge_type, status, generated_by, word_count)
VALUES
('The sun is hot. The sky is blue. I like to run. We have fun. Time flies by. Work is good. Life is great. Try your best.', 'english', 'beginner', 'short', 'general', 'speed', 'ready', 'manual', 30),
('She can type fast. He writes code well. They work hard. Come see us. Read more books. Write every day. Think positive. Stay strong and be kind.', 'english', 'beginner', 'short', 'general', 'speed', 'ready', 'manual', 30);
